<a href="https://colab.research.google.com/github/lee-seong-wook/DAELIM/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
text = '해보지 않으면 해낼 수 없다'
result = text_to_word_sequence(text)
print(result)

['해보지', '않으면', '해낼', '수', '없다']


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다',
        '텍스트의 단어로 토큰화해야 딥러닝에서 인식합니다',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다']
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_counts)

OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식합니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [ ]:
print(token.document_count)

3


In [ ]:
print(token.word_docs)

defaultdict(<class 'int'>, {'나누어': 1, '단어를': 1, '먼저': 1, '토큰화해야': 2, '인식합니다': 2, '딥러닝에서': 3, '단어로': 2, '토큰화합니다': 1, '각': 1, '텍스트의': 2, '결과는': 1, '수': 1, '있습니다': 1, '토큰화한': 1, '사용할': 1})


In [ ]:
text="오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"
token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [ ]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

text = '해보지 않으면 해낼 수 없다'
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])


x = tokenizer.texts_to_sequences([text])


word_size = len(tokenizer.word_index) + 1
x = to_categorical(x, num_classes=word_size)

print(x)


[[[0. 1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 1.]]]


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(16, 4))

In [ ]:
import numpy as np
docs = ['너무 재밌네요','최고에요','참 잘 만든 영화예요','추천하고 싶은 영화입니다.','한번 더 보고싶네요','글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요','재미없네요']
labels = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없네요': 20}


In [ ]:
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np


padded_x = pad_sequences(x,4) #(x, maxlen =4)도 가능함

print(padded_x)


[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [ ]:
word_size = len(token.word_index)+1


In [ ]:
Embedding(word_size, 8, input_length=4)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np


docs = ['너무 재밌네요', '최고에요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다.', '한번 더 보고싶네요', '글쎄요', '별로예요', '생각보다 지루하네요', '연기가 어색해요', '재미없네요']
labels = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])


tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
sequences = tokenizer.texts_to_sequences(docs)

max_sequence_length = 4
padded_sequences = pad_sequences(sequences, maxlen=max_sequence_length)

word_index = tokenizer.word_index
word_size = len(word_index) + 1


model = Sequential()
model.add(Embedding(word_size, 8, input_length=max_sequence_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))


model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


model.fit(padded_sequences, labels, epochs=10)


accuracy = model.evaluate(padded_sequences, labels)[1]
print("\nAccuracy: %.4f" % accuracy)


Epoch 1/10
1/1 [==============================] - 1s 917ms/step - loss: 0.6906 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 0.6889 - accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 13ms/step - loss: 0.6873 - accuracy: 0.5000
Epoch 4/10
1/1 [==============================] - 0s 13ms/step - loss: 0.6856 - accuracy: 0.5000
Epoch 5/10
1/1 [==============================] - 0s 12ms/step - loss: 0.6839 - accuracy: 0.5000
Epoch 6/10
1/1 [==============================] - 0s 12ms/step - loss: 0.6823 - accuracy: 0.6000
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6806 - accuracy: 0.7000
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 0.6790 - accuracy: 0.7000
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6773 - accuracy: 0.7000
Epoch 10/10
1/1 [==============================] - 0s 182ms/step - loss: 0.6740 - accuracy: 0.9000

Accuracy: 0.9000


In [ ]:
from keras.datasets import reuters
(X_train, Y_train),(X_test, Y_test) = reuters.load_data(num_words=1000, test_split=0.2) #num_words는 빈도수를 지정

2110848/2110848 [==============================] - 0s 0us/step


In [ ]:
import numpy as np

category = np.max(Y_train) + 1
print(category, '카테고리')
print(len(X_train), '학습용 뉴스 기사')
print(len(X_test), '테스트용 뉴스 기사')
print(X_train[0])


46 카테고리
8982 학습용 뉴스 기사
2246 테스트용 뉴스 기사
[1, 2, 2, 8, 43, 10, 447, 5, 25, 207, 270, 5, 2, 111, 16, 369, 186, 90, 67, 7, 89, 5, 19, 102, 6, 19, 124, 15, 90, 67, 84, 22, 482, 26, 7, 48, 4, 49, 8, 864, 39, 209, 154, 6, 151, 6, 83, 11, 15, 22, 155, 11, 15, 7, 48, 9, 2, 2, 504, 6, 258, 6, 272, 11, 15, 22, 134, 44, 11, 15, 16, 8, 197, 2, 90, 67, 52, 29, 209, 30, 32, 132, 6, 109, 15, 17, 12]


In [ ]:
from tensorflow.keras.preprocessing import sequence
from keras.utils import np_utils

x_train = sequence.pad_sequences(X_train, maxlen=100)
x_test = sequence.pad_sequences(X_test, maxlen=100)
y_train = np_utils.to_categorical(Y_train)
y_test = np_utils.to_categorical(Y_test)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = Sequential()
model.add(Embedding(1000, 100))
model.add(LSTM(100, activation='tanh'))
model.add(Dense(46, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=100, epochs=20, validation_data=(x_test, y_test))
validation_data = (x_test, y_test)
print("\nTest Accuracy: %.4f" % (model.evaluate(x_test, y_test)[1]))



In [ ]:
from tensorflow.keras.datasets import imdb
(x_train, y_train),(x_test,y_test) = imdb.load_data(num_words=5000)
x_train = sequence.pad_sequences(x_train, maxlen=100)
x_test = sequence.pad_sequences(x_test, maxlen=100)

17464789/17464789 [==============================] - 0s 0us/step


In [ ]:
from tensorflow.keras.layers import Embedding, Dropout, Conv1D, MaxPooling1D, LSTM, Dense, Activation

model = Sequential()
model.add(Embedding(5000,100))
model.add(Dropout(0.5))
model.add(Conv1D(64,5, padding='valid', activation='relu',strides=1))
model.add(MaxPooling1D(pool_size=4))
model.add(LSTM(55))
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, None, 100)         500000    
                                                                 
 dropout_1 (Dropout)         (None, None, 100)         0         
                                                                 
 conv1d_1 (Conv1D)           (None, None, 64)          32064     
                                                                 
 max_pooling1d_1 (MaxPooling  (None, None, 64)         0         
 1D)                                                             
                                                                 
 lstm_2 (LSTM)               (None, 55)                26400     
                                                                 
 dense_2 (Dense)             (None, 1)                 56        
                                                      

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=100, epochs=5, validation_data=(x_test, y_test))
print("\n Test Accuracy:%4f" % (model.evaluate(x_test, y_test)[1]))

Epoch 1/5
250/250 [==============================] - 46s 124ms/step - loss: 0.4567 - accuracy: 0.7693 - val_loss: 0.3373 - val_accuracy: 0.8516
Epoch 2/5
250/250 [==============================] - 11s 43ms/step - loss: 0.2974 - accuracy: 0.8747 - val_loss: 0.3277 - val_accuracy: 0.8559
Epoch 3/5
250/250 [==============================] - 5s 22ms/step - loss: 0.2552 - accuracy: 0.8962 - val_loss: 0.3270 - val_accuracy: 0.8574
Epoch 4/5
250/250 [==============================] - 4s 15ms/step - loss: 0.2210 - accuracy: 0.9127 - val_loss: 0.3393 - val_accuracy: 0.8545
Epoch 5/5
782/782 [==============================] - 4s 4ms/step - loss: 0.3716 - accuracy: 0.8527

 Test Accuracy:0.852680
